# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Search": "cloudsearch.ipynb"}

modules = ["cloudsearch.py"]

doc_url = "https://thanakijwanavit.github.io/cloudsearch/"

git_url = "https://github.com/thanakijwanavit/cloudsearch/tree/master/"

def custom_doc_links(name): return None
